# Generated by Django 6.0.6 on 2026-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_vote_unique_vote_per_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='election_type',
            field=models.CharField(choices=[('delegate', 'Delegate Election'), ('leader', 'Leader Election')], default='leader', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'election', 'position'), name='unique_vote_per_position'),
        ),
    ]
