# Generated by Django 6.0.6 on 2026-07-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_position_election_type_vote_unique_vote_per_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_photos/'),
        ),
    ]
