# Generated by Django 6.0.6 on 2026-07-02 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_holders', to='users.position'),
        ),
    ]
