# Generated by Django 6.0.6 on 2026-07-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_student_current_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
