# Generated by Django 6.0.6 on 2026-07-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_election_is_finalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='election',
            name='is_finalized',
        ),
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('finalized', 'Finalized')], default='draft', max_length=20),
        ),
    ]
