# Generated by Django 6.0.6 on 2026-07-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_position_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the election is currently active.'),
        ),
    ]
