# Generated by Django 6.0.6 on 2026-07-20 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_election_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='is_active',
        ),
        migrations.AddField(
            model_name='position',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='users.election'),
        ),
    ]
