# Generated by Django 6.0.6 on 2026-07-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_position_is_active_position_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='users.election'),
        ),
    ]
